name: Push
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install Dependencies
        run: sudo apt update -y && sudo apt install texlive-full texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra -y 
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Compile
        run: cd tex/ && pdflatex physics.tex -o physics.pdf
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token } 
        with:
          artifacts: "tex/physics.pdf"