name: Push
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: sudo apt update -y && sudo apt install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra -y && sudo tlmgr install mhchem 
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Compile
        run: cd tex/ && pdflatex physics.tex -o physics.pdf
      - name: Create Release
        uses: actions/create-release@v1
        with:
          bodyFile: "tex/physics.pdf"